# Generated by Django 5.0 on 2024-01-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0004_alter_chairman_pic_alter_member_pic_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
